# Ansible Inventory - Список управляемых серверов

all:
  children:
    # Группа серверов для Nginx
    nginx_servers:
      hosts:
        nginx-server:
          ansible_host: 127.0.0.1
          ansible_port: 2221
          ansible_user: ansible
          ansible_password: ansible
          ansible_become: yes
          ansible_become_method: sudo
          http_port: 8083

    # Группа серверов для Apache
    apache_servers:
      hosts:
        apache-server:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: ansible
          ansible_password: ansible
          ansible_become: yes
          ansible_become_method: sudo
          http_port: 8084

  # Общие переменные для всех хостов
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
